# Agent CLI Startup Script — intercom-go
#
# This script is self-contained: it loads .env.local, resolves workspace-local
# AI-tool state directories, runs the sidecar syncs enabled for this workspace
# (backlogit/Engram/graphtor-docs), resolves the Copilot CLI executable, and
# launches it directly in THIS PowerShell host -- no supervising process, no
# process-spawning layer in between. This is deliberate: an intermediate
# process (e.g. a Python launcher) was found to change how many processes are
# attached to the console, which breaks mouse/scroll handling in the launched
# interactive tool. Keeping bootstrap-and-launch native and in-host avoids
# that class of problem entirely.
#
# Usage: ./start.ps1
#
# Auto-MergeInstall / Auto-Tune are GLOBAL agents provided by the autoharness
# marketplace plugin. They are the versions used when upgrading autoharness and
# are intentionally NOT copied into this workspace's local agent config -- a
# stale local copy would shadow the global agent during an upgrade. Upgrade
# them globally with `copilot plugin install autoharness@autoharness`; do not
# run `setup-copilot-cli` here (COPILOT_HOME is redirected to a
# workspace-local dir).
#
# Generated by autoharness. Re-run install or tune to regenerate.
#
# LOCAL DIVERGENCE — re-apply after regeneration (011.018-T, resolves
# 9F9A3CB2). Two local-only improvements on top of the generated template
# that a plain re-render would silently clobber:
#   1. Invoke-EngramCommandWithProgress: a bounded shared wall-clock budget
#      (15000 ms default, ENGRAM_PREWARM_TIMEOUT_MS clamped to 1..30000) for
#      the Engram pre-warm sequence, with a timeout kill, bounded cleanup
#      wait, and an explicit do-not-kill-a-reusable-daemon note.
#   2. Push-Location/Pop-Location in try/finally around the sidecar-sync and
#      launch sequence, so the caller's PowerShell session location is
#      restored even on failure.
# A tracked in-repo follow-up (011.016-T through 011.018-T) records pushing
# both improvements upstream into softwaresalt/autoharness's own template as
# out-of-repository-boundary work.

function Invoke-EngramCommandWithProgress {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Executable,

    [Parameter(Mandatory = $true)]
    [string]$Subcommand,

    [string[]]$GlobalArguments = @(),

    [string[]]$Arguments = @(),

    [Parameter(Mandatory = $true)]
    [string]$Activity,

    [Parameter(Mandatory = $true)]
    [string]$Status,

    [Parameter(Mandatory = $true)]
    [DateTimeOffset]$Deadline
  )

  Write-Host "$Activity — $Status"

  $engramArguments = @("--format", "text")
  $engramArguments += $GlobalArguments
  $engramArguments += $Subcommand
  $engramArguments += $Arguments

  $remainingMs = [Math]::Floor(($Deadline - [DateTimeOffset]::UtcNow).TotalMilliseconds)
  if ($remainingMs -le 0) {
    throw "Engram pre-warm exceeded its shared wall-clock budget before $Subcommand could start."
  }

  $process = $null
  try {
    $processExecutable = $Executable
    $processArguments = $engramArguments
    if ([IO.Path]::GetExtension($Executable) -ieq ".ps1") {
      $pwshCommand = Get-Command pwsh -ErrorAction Stop
      $processExecutable = $pwshCommand.Source
      $processArguments = @("-NoProfile", "-NonInteractive", "-File", $Executable)
      $processArguments += $engramArguments
    }

    $process = Start-Process `
      -FilePath $processExecutable `
      -ArgumentList $processArguments `
      -NoNewWindow `
      -PassThru

    if (-not $process.WaitForExit([int]$remainingMs)) {
      try {
        # Terminate only the command process started above. A daemon-backed
        # command may auto-spawn a reusable daemon that outlives this pre-warm;
        # the launcher does not own that descendant and must not kill it.
        $process.Kill()
        $cleanupTimeoutMs = 1000
        if (-not $process.WaitForExit($cleanupTimeoutMs)) {
          Write-Warning "Timed-out Engram pre-warm process did not exit within $cleanupTimeoutMs ms; continuing fail-open."
        }
      }
      catch {
        Write-Warning "Timed-out Engram pre-warm process cleanup failed: $_"
      }
      throw "engram $Subcommand exceeded the shared Engram pre-warm wall-clock budget."
    }

    if ($process.ExitCode -ne 0) {
      throw "engram $Subcommand failed with exit code $($process.ExitCode)."
    }
  }
  finally {
    if ($null -ne $process) {
      $process.Dispose()
    }
  }
}

# Import-DotEnvLocal loads .env.local (gitignored per-developer overrides) if
# present. Each KEY=VALUE line is exported only when that variable is not
# already set. A single pair of matching surrounding quotes is stripped from
# the value.
#
# 011.017-T (resolves part of 9F9A3CB2): the key regex is
# '[A-Za-z_][A-Za-z0-9_]*' -- widened back from a narrower
# '[A-Z_][A-Z0-9_]*' (uppercase-only) that had regressed onto this script.
# Justified against a concrete key set: GITHUB_PERSONAL_ACCESS_TOKEN and
# GITHUB_TOKEN are themselves all-uppercase, but this loader is a general
# .env.local reader used by any local developer override, and POSIX/.env
# convention (and this repo's own config.toml.example prose) does not
# restrict keys to uppercase; a real lowercase/mixed-case key is a
# reasonably foreseeable local override this loader must not silently drop.
#
# NO-ECHO ENFORCED (011.017-T): this function never Write-Host/Write-Output/
# transcribes any loaded NAME or VALUE. Callers must not do so either.
function Import-DotEnvLocal {
  param(
    [Parameter(Mandatory = $true)]
    [string]$EnvLocalPath
  )

  if (-not (Test-Path -LiteralPath $EnvLocalPath -PathType Leaf)) {
    return
  }

  Get-Content -LiteralPath $EnvLocalPath | ForEach-Object {
    if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
      $name = $matches[1]
      if ($null -eq [Environment]::GetEnvironmentVariable($name, "Process")) {
        $value = $matches[2]
        if ($value.Length -ge 2) {
          $firstChar = $value[0]
          $lastChar = $value[$value.Length - 1]
          if ((($firstChar -eq '"') -or ($firstChar -eq "'")) -and ($lastChar -eq $firstChar)) {
            $value = $value.Substring(1, $value.Length - 2)
          }
        }
        [Environment]::SetEnvironmentVariable($name, $value, "Process")
      }
    }
  }
}

# Resolve-GitHubTokens resolves GitHub tokens via `gh` (011.017-T restores
# GITHUB_PERSONAL_ACCESS_TOKEN resolution). Non-fatal when `gh` is absent or
# failing -- the affected variable is simply left unset.
#
# GITHUB_PERSONAL_ACCESS_TOKEN is UNGUARDED (always re-resolved when `gh` is
# available); GITHUB_TOKEN is GUARDED (no-clobber). This asymmetry is
# intentional, matching each variable's own conventional precedence:
# GITHUB_TOKEN is the widely-recognized ambient variable many tools already
# honor (so an operator-set value must never be clobbered), while
# GITHUB_PERSONAL_ACCESS_TOKEN is this workspace's own resolved-on-each-run
# convention.
#
# NO-ECHO ENFORCED: never Write-Host/Write-Output/transcribe a resolved
# token value. GhExePath is an injectable override purely for testing (a
# fixture "gh" stub); production callers omit it and the real `gh` on PATH
# is used.
function Resolve-GitHubTokens {
  param(
    [string]$GhExePath
  )

  $ghCmd = $null
  if ($GhExePath) {
    if (Test-Path -LiteralPath $GhExePath -PathType Leaf) {
      $ghCmd = [pscustomobject]@{ Source = $GhExePath }
    }
  }
  else {
    $ghCmd = Get-Command gh -ErrorAction SilentlyContinue
  }

  if (-not $ghCmd) {
    return
  }

  try {
    $env:GITHUB_PERSONAL_ACCESS_TOKEN = (& $ghCmd.Source auth token 2>$null).Trim()
  }
  catch {
    Write-Warning "gh auth token failed (non-fatal): $_"
  }

  if (-not $env:GITHUB_TOKEN) {
    try {
      $ghToken = (& $ghCmd.Source auth token 2>$null).Trim()
      if ($ghToken) {
        $env:GITHUB_TOKEN = $ghToken
      }
    }
    catch {
      Write-Warning "gh auth token failed (non-fatal): $_"
    }
  }
}

# Get-EnabledSidecars returns the sidecar syncs enabled for this workspace,
# derived at install time from the capability packs enabled here
# (agent-engram, graphtor-docs, backlogit -- see .autoharness/config.yaml's
# `sidecars` field). This is a template-render-time constant, not a runtime
# YAML parse (PowerShell has no built-in YAML parser without an external
# module) -- re-run install/tune to pick up a changed capability-pack set.
#
# 011.016-T (resolves part of 9F9A3CB2): restores this capability gating so
# sidecars run on INSTALLED capability packs, not mere command presence --
# a `backlogit`/`engram`/`graphtor-docs` binary merely being on PATH (e.g.
# installed globally for an unrelated workspace) must not cause this
# workspace to sync a sidecar its own capability-pack set does not enable.
function Get-EnabledSidecars {
  return @('engram', 'graphtor-docs', 'backlogit')
}

# Resolve-CopilotExecutable resolves the Copilot CLI executable path.
#
# 011.016-T (resolves part of 9F9A3CB2): restores ai_tools.copilot_cli.exe_path
# forwarding -- when .autoharness/config.yaml explicitly configures a
# non-default exe_path, ConfiguredExePath carries that value (rendered at
# install time) so the resolution below picks it up at the same precedence
# tier the operator's own COPILOT_EXE_PATH environment variable would,
# WITHOUT overriding an operator's own already-set COPILOT_EXE_PATH/
# COPILOT_EXE.
function Resolve-CopilotExecutable {
  param(
    [string]$ConfiguredExePath = "copilot"
  )

  if (-not $env:COPILOT_EXE_PATH -and -not $env:COPILOT_EXE) {
    if ($ConfiguredExePath -and ($ConfiguredExePath -ne "copilot")) {
      $env:COPILOT_EXE_PATH = $ConfiguredExePath
    }
  }

  if ($env:COPILOT_EXE_PATH) {
    return $env:COPILOT_EXE_PATH
  }
  if ($env:COPILOT_EXE) {
    return $env:COPILOT_EXE
  }
  $copilotCommand = Get-Command "copilot" -ErrorAction SilentlyContinue
  if ($copilotCommand) { return $copilotCommand.Source }
  return $null
}

# Invoke-BacklogitSync runs `backlogit sync` when the backlogit sidecar is
# enabled and the command is available. BacklogitExePath is an injectable
# override purely for testing.
function Invoke-BacklogitSync {
  param(
    [string[]]$EnabledSidecars,
    [string]$BacklogitExePath
  )

  if ($EnabledSidecars -notcontains "backlogit") {
    return
  }

  $backlogitCmd = $null
  if ($BacklogitExePath) {
    if (Test-Path -LiteralPath $BacklogitExePath -PathType Leaf) {
      $backlogitCmd = [pscustomobject]@{ Source = $BacklogitExePath }
    }
  }
  else {
    $backlogitCmd = Get-Command backlogit -ErrorAction SilentlyContinue
  }

  if (-not $backlogitCmd) {
    return
  }

  try {
    & $backlogitCmd.Source sync
    if ($LASTEXITCODE -ne 0) {
      Write-Warning "backlogit sync exited with code $LASTEXITCODE (non-fatal); index may be stale."
    }
  }
  catch {
    Write-Warning "backlogit sync failed (non-fatal): $_"
  }
}

# Invoke-EngramSync runs the Engram pre-warm sequence (direct, falling back
# to daemon-backed) when the engram sidecar is enabled and the command is
# available. EngramExePath is an injectable override purely for testing.
function Invoke-EngramSync {
  param(
    [string[]]$EnabledSidecars,
    [string]$EngramExePath
  )

  if ($EnabledSidecars -notcontains "engram") {
    return
  }

  $engramCmd = $null
  if ($EngramExePath) {
    if (Test-Path -LiteralPath $EngramExePath -PathType Leaf) {
      $engramCmd = [pscustomobject]@{ Source = $EngramExePath }
    }
  }
  else {
    $engramCmd = Get-Command engram -ErrorAction SilentlyContinue
  }

  if (-not $engramCmd) {
    return
  }

  $prewarmTimeoutMs = 15000
  if ($env:ENGRAM_PREWARM_TIMEOUT_MS) {
    $configuredTimeoutMs = 0
    if (
      [int]::TryParse($env:ENGRAM_PREWARM_TIMEOUT_MS, [ref]$configuredTimeoutMs) -and
      $configuredTimeoutMs -gt 0 -and
      $configuredTimeoutMs -le 30000
    ) {
      $prewarmTimeoutMs = $configuredTimeoutMs
    }
    else {
      Write-Warning "Ignoring invalid ENGRAM_PREWARM_TIMEOUT_MS; expected 1..30000 milliseconds."
    }
  }
  $prewarmDeadline = [DateTimeOffset]::UtcNow.AddMilliseconds($prewarmTimeoutMs)

  try {
    Invoke-EngramCommandWithProgress `
      -Executable $engramCmd.Source `
      -Subcommand "sync" `
      -GlobalArguments @("--timeout", "300") `
      -Arguments @("--direct") `
      -Activity "Synchronizing Engram index" `
      -Status "Direct pre-warm before Copilot startup" `
      -Deadline $prewarmDeadline
  }
  catch {
    Write-Warning "engram direct pre-warm failed; retrying via daemon sync: $_"
    try {
      Invoke-EngramCommandWithProgress `
        -Executable $engramCmd.Source `
        -Subcommand "bind" `
        -Activity "Binding Engram workspace" `
        -Status "Daemon-backed pre-warm fallback" `
        -Deadline $prewarmDeadline
      Invoke-EngramCommandWithProgress `
        -Executable $engramCmd.Source `
        -Subcommand "sync" `
        -GlobalArguments @("--timeout", "300") `
        -Activity "Synchronizing Engram index" `
        -Status "Daemon-backed pre-warm fallback" `
        -Deadline $prewarmDeadline
    }
    catch {
      Write-Warning "engram sync failed (non-fatal): $_"
    }
  }
}

# Resolve-GraphtorDocsCommand resolves the graphtor-docs command: a PATH
# lookup first, falling back to the workspace-local
# .graphtor/bin/graphtor-docs.exe install location.
#
# 011.016-T (resolves part of 9F9A3CB2): restores this fallback -- its
# removal directly contradicted this same change set's .gitignore addition
# of .graphtor/ (011.015-T), which only makes sense if something actually
# looks for a binary there.
function Resolve-GraphtorDocsCommand {
  param(
    [Parameter(Mandatory = $true)]
    [string]$ScriptRoot
  )

  $graphtorDocsCmd = Get-Command graphtor-docs -ErrorAction SilentlyContinue
  if (-not $graphtorDocsCmd) {
    $localGraphtorDocs = Join-Path $ScriptRoot ".graphtor\bin\graphtor-docs.exe"
    if (Test-Path -LiteralPath $localGraphtorDocs -PathType Leaf) {
      $graphtorDocsCmd = [pscustomobject]@{ Source = $localGraphtorDocs }
    }
  }
  return $graphtorDocsCmd
}

# Invoke-GraphtorDocsSync runs `graphtor-docs sync` when the graphtor-docs
# sidecar is enabled and a command is resolved (PATH or local fallback).
function Invoke-GraphtorDocsSync {
  param(
    [string[]]$EnabledSidecars,
    [Parameter(Mandatory = $true)]
    [string]$ScriptRoot
  )

  if ($EnabledSidecars -notcontains "graphtor-docs") {
    return
  }

  $graphtorDocsCmd = Resolve-GraphtorDocsCommand -ScriptRoot $ScriptRoot
  if (-not $graphtorDocsCmd) {
    return
  }

  try {
    & $graphtorDocsCmd.Source sync
  }
  catch {
    Write-Warning "graphtor-docs sync failed (non-fatal): $_"
  }
}

# Invoke-StartScriptMain is the full orchestration entry point, factored out
# so this file can be dot-sourced (for testing each function above in
# isolation) without triggering the real launch sequence. See the
# `$MyInvocation.InvocationName -ne '.'` guard at the bottom of this file.
function Invoke-StartScriptMain {
  param(
    [string[]]$LaunchArguments = @()
  )

  Import-DotEnvLocal -EnvLocalPath (Join-Path $PSScriptRoot ".env.local")

  # COPILOT_HOME/ENGRAM_DATA_DIR redirect AI-tool state to workspace-local
  # hidden directories so agent memories, checkpoints, and database files
  # are git-visible and project-scoped rather than shared across all
  # workspaces.
  $env:COPILOT_HOME = if ($env:COPILOT_HOME) { $env:COPILOT_HOME } else { Join-Path $PSScriptRoot ".copilot" }
  $env:ENGRAM_DATA_DIR = if ($env:ENGRAM_DATA_DIR) { $env:ENGRAM_DATA_DIR } else { Join-Path $PSScriptRoot ".engram" }

  Resolve-GitHubTokens

  $copilotExe = Resolve-CopilotExecutable -ConfiguredExePath "copilot"
  if (-not $copilotExe) {
    Write-Error "Unable to locate Copilot CLI. Set COPILOT_EXE_PATH (or COPILOT_EXE for backward compatibility) or add 'copilot' to PATH."
    exit 1
  }

  $enabledSidecars = Get-EnabledSidecars

  # Anchor workspace operations (backlogit, engram, Copilot) to the repo dir
  # for the duration of the launched commands, then restore the caller's
  # location. The current location is runspace state (not script-scoped),
  # so Push/Pop in a finally keeps the caller's PowerShell session location
  # unchanged even on failure (LOCAL DIVERGENCE improvement #2, see banner
  # above).
  Push-Location -LiteralPath $PSScriptRoot
  try {
    Invoke-BacklogitSync -EnabledSidecars $enabledSidecars
    Invoke-EngramSync -EnabledSidecars $enabledSidecars
    Invoke-GraphtorDocsSync -EnabledSidecars $enabledSidecars -ScriptRoot $PSScriptRoot

    # ai_tools.copilot_cli.args from .autoharness/config.yaml -- extra
    # arguments always passed before the operator's own argv. Forwarded as
    # opt-in only via the operator's own args here: no extra args are
    # force-injected by this template render.
    $copilotArguments = @()
    $copilotArguments += $LaunchArguments

    & $copilotExe @copilotArguments
    # 011.017-T (resolves part of 9F9A3CB2): trailing exit-code propagation
    # restored -- the launcher's own process exit code must reflect the
    # launched Copilot CLI's exit code, not merely whatever PowerShell's
    # implicit last-command status happens to be by the time this script
    # returns.
    exit $LASTEXITCODE
  }
  finally {
    Pop-Location
  }
}

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# $env:CLAUDE_CONFIG_DIR = ".\.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# $env:OPENAI_API_KEY = (Get-Content .openai-token -Raw).Trim()
# codex

if ($MyInvocation.InvocationName -ne '.') {
  Invoke-StartScriptMain -LaunchArguments $args
}
