# Agent CLI Startup Script — intercom-go
#
# This script is self-contained: it loads .env.local, resolves workspace-local
# AI-tool state directories, runs the sidecar syncs enabled for this workspace
# (backlogit/Engram/graphtor-docs), resolves the Copilot CLI executable, and
# launches it directly in THIS PowerShell host -- no supervising process, no
# process-spawning layer in between. This is deliberate: an intermediate
# process (e.g. a Python launcher) was found to change how many processes are
# attached to the console, which breaks mouse/scroll handling in the launched
# interactive tool. Keeping bootstrap-and-launch native and in-host avoids
# that class of problem entirely.
#
# Usage: ./start.ps1
#
# Auto-MergeInstall / Auto-Tune are GLOBAL agents provided by the autoharness
# marketplace plugin. They are the versions used when upgrading autoharness and
# are intentionally NOT copied into this workspace's local agent config -- a
# stale local copy would shadow the global agent during an upgrade. Upgrade
# them globally with `copilot plugin install autoharness@autoharness`.
#
# Generated by autoharness. Re-run install or tune to regenerate.

# Load .env.local (gitignored per-developer overrides) if present. Each
# KEY=VALUE line is exported only when that variable is not already set. A
# single pair of matching surrounding quotes is stripped from the value.
$envLocalPath = Join-Path $PSScriptRoot ".env.local"
if (Test-Path -LiteralPath $envLocalPath -PathType Leaf) {
    Get-Content -LiteralPath $envLocalPath | ForEach-Object {
        if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
            $name = $matches[1]
            if ($null -eq [Environment]::GetEnvironmentVariable($name, "Process")) {
                $value = $matches[2]
                if ($value.Length -ge 2) {
                    $firstChar = $value[0]
                    $lastChar = $value[$value.Length - 1]
                    if ((($firstChar -eq '"') -or ($firstChar -eq "'")) -and ($lastChar -eq $firstChar)) {
                        $value = $value.Substring(1, $value.Length - 2)
                    }
                }
                [Environment]::SetEnvironmentVariable($name, $value, "Process")
            }
        }
    }
}

# COPILOT_HOME/ENGRAM_DATA_DIR redirect AI-tool state to workspace-local hidden
# directories so agent memories, checkpoints, and database files are
# git-visible and project-scoped rather than shared across all workspaces.
$env:COPILOT_HOME = if ($env:COPILOT_HOME) { $env:COPILOT_HOME } else { Join-Path $PSScriptRoot ".copilot" }
$env:ENGRAM_DATA_DIR = if ($env:ENGRAM_DATA_DIR) { $env:ENGRAM_DATA_DIR } else { Join-Path $PSScriptRoot ".engram" }

# GitHub token resolution via `gh`. Non-fatal when `gh` is absent or failing --
# the affected variable is simply left unset. GITHUB_PERSONAL_ACCESS_TOKEN is
# unguarded (always re-resolved when `gh` is available); GITHUB_TOKEN is
# guarded (no-clobber) -- this asymmetry is intentional, matching each
# variable's own conventional precedence.
$ghCmd = Get-Command gh -ErrorAction SilentlyContinue
if ($ghCmd) {
    try {
        $env:GITHUB_PERSONAL_ACCESS_TOKEN = (& $ghCmd.Source auth token 2>$null).Trim()
    } catch {
        Write-Warning "gh auth token failed (non-fatal): $_"
    }
    if (-not $env:GITHUB_TOKEN) {
        try {
            $ghToken = (& $ghCmd.Source auth token 2>$null).Trim()
            if ($ghToken) {
                $env:GITHUB_TOKEN = $ghToken
            }
        } catch {
            Write-Warning "gh auth token failed (non-fatal): $_"
        }
    }
}

# ai_tools.copilot_cli.exe_path from .autoharness/config.yaml, when
# explicitly configured to something other than a bare PATH lookup, is
# forwarded as an environment default so the resolution below picks it up
# at the same precedence tier the operator's own environment would.
if (-not $env:COPILOT_EXE_PATH -and -not $env:COPILOT_EXE) {
    $defaultCopilotExe = "copilot"
    if ($defaultCopilotExe -and ($defaultCopilotExe -ne "copilot")) {
        $env:COPILOT_EXE_PATH = $defaultCopilotExe
    }
}

$copilotExe = if ($env:COPILOT_EXE_PATH) {
    $env:COPILOT_EXE_PATH
} elseif ($env:COPILOT_EXE) {
    $env:COPILOT_EXE
} else {
    $copilotCommand = Get-Command "copilot" -ErrorAction SilentlyContinue
    if ($copilotCommand) { $copilotCommand.Source } else { $null }
}

if (-not $copilotExe) {
    Write-Error "Unable to locate Copilot CLI. Set COPILOT_EXE_PATH (or COPILOT_EXE for backward compatibility) or add 'copilot' to PATH."
    exit 1
}

# Sidecar syncs -- derived at install time from the capability packs enabled
# for this workspace (backlogit/agent-engram/graphtor-docs).
$enabledSidecars = @('engram', 'graphtor-docs', 'backlogit')

if ($enabledSidecars -contains "backlogit") {
    $backlogitCmd = Get-Command backlogit -ErrorAction SilentlyContinue
    if ($backlogitCmd) {
        try {
            & $backlogitCmd.Source sync
        } catch {
            Write-Warning "backlogit sync failed (non-fatal): $_"
        }
    }
}

if ($enabledSidecars -contains "engram") {
    $engramCmd = Get-Command engram -ErrorAction SilentlyContinue
    if ($engramCmd) {
        try {
            Write-Host "Synchronizing Engram index — Direct pre-warm before Copilot startup"
            & $engramCmd.Source --format text sync --timeout 300 --direct
            if ($LASTEXITCODE -ne 0) {
                throw "engram sync failed with exit code $LASTEXITCODE."
            }
        } catch {
            Write-Warning "engram direct pre-warm failed; retrying via daemon sync: $_"
            try {
                & $engramCmd.Source --format text bind
                Write-Host "Synchronizing Engram index — Daemon-backed pre-warm fallback"
                & $engramCmd.Source --format text sync --timeout 300
                if ($LASTEXITCODE -ne 0) {
                    throw "engram sync failed with exit code $LASTEXITCODE."
                }
            } catch {
                Write-Warning "engram sync failed (non-fatal): $_"
            }
        }
    }
}

if ($enabledSidecars -contains "graphtor-docs") {
    $graphtorDocsCmd = Get-Command graphtor-docs -ErrorAction SilentlyContinue
    if (-not $graphtorDocsCmd) {
        $localGraphtorDocs = Join-Path $PSScriptRoot ".graphtor\bin\graphtor-docs.exe"
        if (Test-Path -LiteralPath $localGraphtorDocs -PathType Leaf) {
            $graphtorDocsCmd = [pscustomobject]@{ Source = $localGraphtorDocs }
        }
    }
    if ($graphtorDocsCmd) {
        try {
            & $graphtorDocsCmd.Source sync
        } catch {
            Write-Warning "graphtor-docs sync failed (non-fatal): $_"
        }
    }
}

# ai_tools.copilot_cli.args from .autoharness/config.yaml -- extra arguments
# always passed before the operator's own argv (e.g. ["--remote"]).
$copilotArguments = @()
$copilotArguments += $args

& $copilotExe @copilotArguments
exit $LASTEXITCODE

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# $env:CLAUDE_CONFIG_DIR = ".\.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# $env:OPENAI_API_KEY = (Get-Content .openai-token -Raw).Trim()
# codex

