package pysem

import "unicode"

// otherLowerTable and otherUpperTable hold the codepoints that carry
// Unicode's derived Lowercase / Uppercase property WITHOUT belonging to
// General_Category Ll / Lu respectively -- CPython's str.islower() and
// str.isupper() single-character checks test the derived property, not
// General_Category alone, so unicode.IsLower / unicode.IsUpper (which are
// Ll/Lu-only) under-match without these supplements (observed via
// U+2071 SUPERSCRIPT LATIN SMALL LETTER I, category Lm, which
// '\u2071'.islower() reports True for in CPython but unicode.IsLower does
// not).
//
// Generated by a transient, uncommitted script (plan C-5: "no .py file is
// added") equivalent to:
//
//	for cp in range(0x110000):
//	    ch = chr(cp)
//	    if ch.islower() and unicodedata.category(ch) != 'Ll':
//	        extra_lower.append(cp)
//	    if ch.isupper() and unicodedata.category(ch) != 'Lu':
//	        extra_upper.append(cp)
//
// against CPython 3.14.3 / unicodedata 16.0.0 (311 extra-lower / 120
// extra-upper codepoints; see
// docs/plans/evidence/2026-09-28-gate-engine-go-migration/m1.md for the
// full generator listing). otherLowerTable covers Latin/Greek/IPA modifier
// letters, small Roman numerals, and circled/parenthesized Latin small
// letters; otherUpperTable covers Roman numerals and circled/squared Latin
// capital letters. All are long-established legacy assignments predating
// Unicode 15.0.
var otherLowerTable = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 0x00AA, Hi: 0x00AA, Stride: 1},
		{Lo: 0x00BA, Hi: 0x00BA, Stride: 1},
		{Lo: 0x02B0, Hi: 0x02B8, Stride: 1},
		{Lo: 0x02C0, Hi: 0x02C1, Stride: 1},
		{Lo: 0x02E0, Hi: 0x02E4, Stride: 1},
		{Lo: 0x0345, Hi: 0x0345, Stride: 1},
		{Lo: 0x037A, Hi: 0x037A, Stride: 1},
		{Lo: 0x10FC, Hi: 0x10FC, Stride: 1},
		{Lo: 0x1D2C, Hi: 0x1D6A, Stride: 1},
		{Lo: 0x1D78, Hi: 0x1D78, Stride: 1},
		{Lo: 0x1D9B, Hi: 0x1DBF, Stride: 1},
		{Lo: 0x2071, Hi: 0x2071, Stride: 1},
		{Lo: 0x207F, Hi: 0x207F, Stride: 1},
		{Lo: 0x2090, Hi: 0x209C, Stride: 1},
		{Lo: 0x2170, Hi: 0x217F, Stride: 1},
		{Lo: 0x24D0, Hi: 0x24E9, Stride: 1},
		{Lo: 0x2C7C, Hi: 0x2C7D, Stride: 1},
		{Lo: 0xA69C, Hi: 0xA69D, Stride: 1},
		{Lo: 0xA770, Hi: 0xA770, Stride: 1},
		{Lo: 0xA7F2, Hi: 0xA7F4, Stride: 1},
		{Lo: 0xA7F8, Hi: 0xA7F9, Stride: 1},
		{Lo: 0xAB5C, Hi: 0xAB5F, Stride: 1},
		{Lo: 0xAB69, Hi: 0xAB69, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 0x10780, Hi: 0x10780, Stride: 1},
		{Lo: 0x10783, Hi: 0x10785, Stride: 1},
		{Lo: 0x10787, Hi: 0x107B0, Stride: 1},
		{Lo: 0x107B2, Hi: 0x107BA, Stride: 1},
		{Lo: 0x1E030, Hi: 0x1E06D, Stride: 1},
	},
	LatinOffset: 2, // {0x00AA,0x00AA} and {0x00BA,0x00BA} are both <= MaxLatin1.
}

var otherUpperTable = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 0x2160, Hi: 0x216F, Stride: 1},
		{Lo: 0x24B6, Hi: 0x24CF, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 0x1F130, Hi: 0x1F149, Stride: 1},
		{Lo: 0x1F150, Hi: 0x1F169, Stride: 1},
		{Lo: 0x1F170, Hi: 0x1F189, Stride: 1},
	},
	LatinOffset: 0,
}
