package pysem

import "unicode"

// extraDigit is the set of runes that satisfy CPython's str.isdigit() but
// NOT str.isdecimal() -- i.e. Unicode's Numeric_Type=Digit codepoints that
// are outside General_Category=Nd (which unicode.IsDigit / IsDecimal
// already covers). Go's stdlib unicode package has no ready-made table for
// Numeric_Type=Digit, so this table is machine-generated once from CPython
// and checked in as a plain Go source file (never as data read at runtime).
//
// Generated by a transient, uncommitted script (plan C-5: "no .py file is
// added") equivalent to:
//
//	for cp in range(0x110000):
//	    ch = chr(cp)
//	    if ch.isdigit() and not ch.isdecimal():
//	        extra.append(cp)
//
// against CPython 3.14.3 / unicodedata 16.0.0 (see
// docs/plans/evidence/2026-09-28-gate-engine-go-migration/m1.md for the
// full generator listing and the 128-codepoint / 20-range output this
// table encodes). Every codepoint below is a long-established legacy
// assignment (superscript/subscript digits, circled and parenthesized
// digits, Ethiopic/Kharoshthi/Rumi/Brahmi digits, dingbat digits, and the
// "digit + punctuation" enclosed-alphanumeric block); none postdates
// Unicode 15.0, so Go's own (15.0.0) unicode tables already recognize
// every one of them as assigned.
var extraDigit = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 0x00B2, Hi: 0x00B3, Stride: 1},
		{Lo: 0x00B9, Hi: 0x00B9, Stride: 1},
		{Lo: 0x1369, Hi: 0x1371, Stride: 1},
		{Lo: 0x19DA, Hi: 0x19DA, Stride: 1},
		{Lo: 0x2070, Hi: 0x2070, Stride: 1},
		{Lo: 0x2074, Hi: 0x2079, Stride: 1},
		{Lo: 0x2080, Hi: 0x2089, Stride: 1},
		{Lo: 0x2460, Hi: 0x2468, Stride: 1},
		{Lo: 0x2474, Hi: 0x247C, Stride: 1},
		{Lo: 0x2488, Hi: 0x2490, Stride: 1},
		{Lo: 0x24EA, Hi: 0x24EA, Stride: 1},
		{Lo: 0x24F5, Hi: 0x24FD, Stride: 1},
		{Lo: 0x24FF, Hi: 0x24FF, Stride: 1},
		{Lo: 0x2776, Hi: 0x277E, Stride: 1},
		{Lo: 0x2780, Hi: 0x2788, Stride: 1},
		{Lo: 0x278A, Hi: 0x2792, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 0x10A40, Hi: 0x10A43, Stride: 1},
		{Lo: 0x10E60, Hi: 0x10E68, Stride: 1},
		{Lo: 0x11052, Hi: 0x1105A, Stride: 1},
		{Lo: 0x1F100, Hi: 0x1F10A, Stride: 1},
	},
	LatinOffset: 2, // {0x00B2,0x00B3} and {0x00B9,0x00B9} are both <= MaxLatin1.
}
