#!/usr/bin/env bash
# ci-topology-check.sh
# Generated by autoharness | Template: ci/ci-topology-check.sh.tmpl
#
# CI topology-check entrypoint (109.011-T / Shipment C, gate C of the staged
# A->B->C `autoharness gate pipeline-topology` rollout). This is the
# server-side backstop for the P-001 (at-most-one-active-shipment) / P-016
# (single implementation worktree/branch) invariants: local hooks
# (pre-commit-pipeline-topology.*, pre-push-quality-gates.*) are
# advisory-first and always bypassable via `git ... --no-verify`, and Git has
# no pre-worktree-add hook at all. CI is the re-validation point for those
# gaps.
#
# THREAT MODEL / LIMITS: this is NOT a non-bypassable backstop against a
# malicious or compromised pull request. GitHub's `pull_request` trigger
# loads and runs this very script (and the workflow job invoking it) from the
# PR's own proposed head, so a PR that violates topology invariants can also
# edit this script or the workflow to trivially report success. It IS an
# effective backstop against accidental/careless local bypasses that were
# never intended to touch the enforcement surface itself. See "Threat Model &
# CODEOWNERS Hardening" in docs/pipeline-topology-gate-ci-rollout.md for the
# recommended mitigation (protect this file and the CI workflow with a
# CODEOWNERS-required review) and for a stronger, out-of-scope alternative
# (`pull_request_target`-based re-architecture).
#
# NON-SHIPMENT-SCOPED INVOCATION: no human-supplied --shipment is passed, and
# no --shipment is resolved from CI job inputs. The gate deterministically
# resolves its own target the SAME way the local ambient hooks do: (1) the
# currently-claimed active shipment recorded in the SYNCED resolved backlog
# root (`.backlog/` for new installs, `.backlogit/` for legacy workspaces, or
# `BACKLOGIT_WORKSPACE_DIR` when explicitly overridden), or (2) failing that,
# the branch under validation. The phase is always `ambient`. Per the phase
# semantics matrix
# (docs/pipeline-topology-gate.md): zero active shipments / no resolvable
# target PASSES (ordinary CI stays non-blocking for commits with no claimed
# shipment); a single active shipment matching the resolved target PASSES; a
# mismatched single active shipment, or two-or-more active shipments, BLOCKS
# regardless of the required-vs-advisory workflow toggle (the toggle decides
# whether a BLOCK fails the CI *job*, never whether the gate itself reports
# BLOCK).
#
# DETECT-AT-SYNC, NOT A LOCK: this is an honest re-validation of backlogit
# state as committed in the checked-out (synced) repo -- it catches topology
# divergence when checkouts converge in CI/merge. It is NOT a lock, lease, or
# real-time serialization (per 012-DL / 109-F's documented local+cross-machine
# TOCTOU limitation); concurrent claims from a different, not-yet-synced
# checkout can still race ahead of this check. Fail-closed on any ambiguity.
#
# DOES NOT DEPEND ON MACHINE-LOCAL WORKTREE STATE: `pipeline-topology`'s
# worktree-uniqueness check (P-016) is scoped to the invoking machine's own
# `git worktree list`, which is meaningless across a CI runner's ephemeral,
# single-checkout filesystem. This entrypoint deliberately runs `--phase
# ambient` (which validates the active-shipment + branch-ownership invariants
# for the resolved target) rather than a shipment-scoped phase; it does not
# assert or depend on any particular worktree count on the runner.
#
# FAIL-CLOSED, NO ADVISORY-DEGRADE (unlike the local pre-commit/pre-push
# hooks, which default to advisory/non-blocking and are missing-tool-tolerant
# for a developer machine that may legitimately lack the CLI): this
# entrypoint ALWAYS propagates the gate's raw exit code unmodified, and
# treats a missing `autoharness` binary as a CI configuration failure (exit 1),
# not a warn-and-skip case. The required-vs-advisory TOGGLE lives one layer
# up, in the CI WORKFLOW job that invokes this script (job-level
# `continue-on-error`, gated on the `PIPELINE_TOPOLOGY_GATE_REQUIRED`
# repository variable) -- see the `topology-check` job added to
# `templates/ci/ci.yml.tmpl` (109.014-T / C2) and
# `docs/pipeline-topology-gate.md`.
#
# Exit codes (propagated unmodified from `autoharness gate pipeline-topology`):
#   0  PASS  -- no active shipment (ordinary CI run, non-blocking) or the
#              resolved target's ambient invariants all held.
#   1  BLOCK -- a mismatched single active shipment, two-or-more active
#              shipments, or another ambient invariant failed.
#   2  invalid gate invocation/configuration (should not occur with the
#      fixed flags below; fails closed if it somehow does).
#
# Reuses the gate core built in Shipment A (`autoharness.gates.topology`) --
# no new gate logic is introduced here; this script is a thin, fail-closed CI
# wrapper around the existing `autoharness gate pipeline-topology` CLI.

set -uo pipefail

# Run from repo root so repo-root-relative backlog-root resolution is valid.
cd "$(git rev-parse --show-toplevel)" || exit 1

if ! command -v autoharness >/dev/null 2>&1; then
  echo "::error::'autoharness' not found on PATH -- the CI topology-check entrypoint requires the package to be installed as a prior workflow step (CI configuration failure, not an advisory skip)." >&2
  exit 1
fi

if [ "${BACKLOGIT_WORKSPACE_DIR+x}" = "x" ]; then
  if [ -z "$BACKLOGIT_WORKSPACE_DIR" ]; then
    echo "::error::[CI Topology Check] BACKLOGIT_WORKSPACE_DIR is set but empty." >&2
    exit 1
  elif [ "$BACKLOGIT_WORKSPACE_DIR" != ".backlog" ] && [ "$BACKLOGIT_WORKSPACE_DIR" != ".backlogit" ]; then
    # Mirrors backlogit 1.9.0's own validateWorkspaceDirOverride
    # (internal/core/workspace.go): the override is NOT an arbitrary
    # filesystem path -- it must be exactly one of the two supported literal
    # candidate names (case-sensitive). This single exact-string comparison
    # rejects path separators, "." / "..", absolute paths, drive/UNC
    # prefixes, and case aliases in one step, since none of those values can
    # ever equal ".backlog" or ".backlogit" verbatim (PR #344 Copilot review,
    # thread PRRT_kwDORzpWpM6ZihN-).
    echo "::error::[CI Topology Check] BACKLOGIT_WORKSPACE_DIR must be exactly .backlog or .backlogit (got: $BACKLOGIT_WORKSPACE_DIR)." >&2
    exit 1
  elif [ ! -d "$BACKLOGIT_WORKSPACE_DIR" ]; then
    echo "::error::[CI Topology Check] BACKLOGIT_WORKSPACE_DIR points to a missing directory: $BACKLOGIT_WORKSPACE_DIR" >&2
    exit 1
  fi
  backlog_dir="$BACKLOGIT_WORKSPACE_DIR"
elif [ -d .backlog ] && [ -d .backlogit ]; then
  echo "::error::[CI Topology Check] both .backlog and .backlogit are present; resolve the ambiguity before running the topology gate." >&2
  exit 1
elif [ -d .backlog ]; then
  backlog_dir=".backlog"
  export BACKLOGIT_WORKSPACE_DIR="$backlog_dir"
elif [ -d .backlogit ]; then
  backlog_dir=".backlogit"
  export BACKLOGIT_WORKSPACE_DIR="$backlog_dir"
else
  backlog_dir="(unavailable)"
fi

echo "[CI Topology Check] resolved backlog root: ${backlog_dir}"
echo "[CI Topology Check] autoharness gate pipeline-topology --mode ci --phase ambient --json"
autoharness gate pipeline-topology --mode ci --phase ambient --json
exit_code=$?

if [ "$exit_code" -eq 0 ]; then
  echo "[CI Topology Check] PASS"
elif [ "$exit_code" -eq 1 ]; then
  echo "::error::[CI Topology Check] BLOCK -- pipeline-topology invariant violated (P-001/P-016 server-side backstop). See docs/pipeline-topology-gate.md." >&2
else
  echo "::error::[CI Topology Check] INVALID (exit ${exit_code}) -- gate invocation/configuration error." >&2
fi

exit "$exit_code"
