#!/usr/bin/env bash
# deploy-harness.sh — scripted install/deploy for intercom-go
#
# Deterministic bootstrap-and-deploy wrapper for autoharness. It collapses the
# scattered "install tool -> register environment -> configure packs -> run
# installer" sequence into one idempotent, documented command, then HANDS OFF
# template composition to the AI-agent installer.
#
# Six phases (decision D2):
#   preflight  -> verify prerequisites (fail closed on missing hard prereqs)
#   bootstrap  -> locate/acquire autoharness_home (global; opt-in via --bootstrap)
#   register   -> run autoharness setup-* / copilot plugin install
#   scaffold   -> write .autoharness/config.yaml (preset + resolved capability packs)
#   compose    -> HANDOFF ONLY: print the /install-harness command; NO template
#                 resolution happens here (that is the agent's job)
#   verify     -> optional deterministic `autoharness verify-workspace`
#
# Additive checklist phase (114-F / 47971057 bounded, non-D2): runs after
# preflight and before bootstrap. Detects per-pack PRESENCE and VERSION for
# backlogit/engram/graphtor-docs (`<tool> --version`; graphtor-docs also checks
# the workspace-local .graphtor/bin/ path) and prints a REPORT-ONLY recommended
# action per pack (retain-present / needs-install[deferred] /
# unsupported-undetectable). It performs NO install/upgrade/provisioning.
# Interactive check/uncheck prompts are opt-in via --interactive; the default
# is a non-interactive report so headless/CI deploys never regress. Actual
# runtime provisioning execution and its open design questions remain
# DEFERRED to operator — see
# docs/decisions/2026-08-07-capability-pack-runtime-installer-deliberation.md.
#
# The scaffold/verify phases write ONLY inside the current workspace (cwd). The
# bootstrap phase installs a GLOBAL tool OUTSIDE cwd BY DESIGN and is therefore
# gated behind an explicit --bootstrap opt-in. --dry-run prints the plan without
# mutating anything. Single deterministic pass per phase (no internal retry loop).
#
# Idempotent: an existing autoharness_home is detected and reused; an existing
# .autoharness/config.yaml is backed up (timestamped) before overwrite and only
# overwritten with --force; an existing .env.local is never clobbered.
#
# Usage: ./deploy-harness.sh [--preset P] [--packs all|a,b] [--register ENV]
#          [--install-method pip|clone] [--home PATH] [--bootstrap]
#          [--interactive] [--dry-run] [--force]
#   Requires execute permission on first use: chmod +x deploy-harness.sh
#
# Exit codes:
#   0  success
#   1  preflight failure (missing hard prerequisite)
#   2  bootstrap failure (autoharness_home not found and not authorized to install)
#   3  register failure
#   4  scaffold failure
#   5  verify failure
#
# Generated by autoharness. Re-run install or tune to regenerate.

set -euo pipefail

PRESET="full"
PACKS=""
REGISTER="copilot-cli"
INSTALL_METHOD="pip"
HOME_OVERRIDE=""
BOOTSTRAP=0
INTERACTIVE=0
DRY_RUN=0
FORCE=0
PYTHON_BIN=""

WORKSPACE_ROOT="$(pwd)"
AUTOHARNESS_HOME_DEFAULT="~/.autoharness"
PACK_REGISTRY_REL_PATH="templates/packs/capability-pack-registry.yaml"

phase()  { printf '== %s ==\n' "$1"; }
ok()     { printf '  [OK]   %s\n' "$1"; }
info()   { printf '  [..]   %s\n' "$1"; }
warn()   { printf '  [WARN] %s\n' "$1" >&2; }
fail()   { printf '  [FAIL] %s\n' "$1" >&2; }

while [[ $# -gt 0 ]]; do
	case "$1" in
		--preset) PRESET="$2"; shift 2 ;;
		--packs) PACKS="$2"; shift 2 ;;
		--register) REGISTER="$2"; shift 2 ;;
		--install-method) INSTALL_METHOD="$2"; shift 2 ;;
		--home) HOME_OVERRIDE="$2"; shift 2 ;;
		--bootstrap) BOOTSTRAP=1; shift ;;
		--interactive) INTERACTIVE=1; shift ;;
		--dry-run) DRY_RUN=1; shift ;;
		--force) FORCE=1; shift ;;
		-h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*) fail "unknown argument: $1"; exit 1 ;;
	esac
done

case "$PRESET" in starter|standard|full) ;; *) fail "invalid --preset: $PRESET"; exit 1 ;; esac
case "$REGISTER" in vscode|copilot-cli|claude|codex|none) ;; *) fail "invalid --register: $REGISTER"; exit 1 ;; esac
case "$INSTALL_METHOD" in pip|clone) ;; *) fail "invalid --install-method: $INSTALL_METHOD"; exit 1 ;; esac

# Load .env.local (gitignored per-developer overrides) if present, mirroring the
# start.sh loader: export each KEY=VALUE only when not already set; strip a
# single pair of matching surrounding quotes.
env_local="${WORKSPACE_ROOT}/.env.local"
if [[ -f "$env_local" ]]; then
	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
			env_name="${BASH_REMATCH[1]}"
			env_value="${BASH_REMATCH[2]}"
			env_value="${env_value%$'\r'}"
			env_value="${env_value%"${env_value##*[![:space:]]}"}"
			if [[ ${#env_value} -ge 2 && "${env_value:0:1}" == "${env_value: -1}" && ( "${env_value:0:1}" == '"' || "${env_value:0:1}" == "'" ) ]]; then
				env_value="${env_value:1:${#env_value}-2}"
			fi
			if [[ -z "${!env_name+x}" ]]; then
				export "$env_name=$env_value"
			fi
		fi
	done < "$env_local"
fi

resolve_home() {
	# Resolution order: --home -> AUTOHARNESS_HOME env -> `autoharness home` CLI
	# -> default. Echoes the resolved path or empty string.
	if [[ -n "$HOME_OVERRIDE" ]]; then echo "$HOME_OVERRIDE"; return; fi
	if [[ -n "${AUTOHARNESS_HOME:-}" ]]; then echo "$AUTOHARNESS_HOME"; return; fi
	if command -v autoharness >/dev/null 2>&1; then
		local resolved
		resolved="$(autoharness home 2>/dev/null | head -n1 || true)"
		if [[ -n "$resolved" ]]; then echo "$resolved"; return; fi
	fi
	if [[ -d "$AUTOHARNESS_HOME_DEFAULT" ]]; then echo "$AUTOHARNESS_HOME_DEFAULT"; return; fi
	echo ""
}

registry_packs() {
	# Enumerate pack ids from the plain-YAML registry with a deterministic line
	# scan (no YAML module dependency).
	local home_path="$1"
	[[ -z "$home_path" ]] && return 0
	local registry="${home_path}/${PACK_REGISTRY_REL_PATH}"
	[[ -f "$registry" ]] || return 0
	sed -n 's/^[[:space:]]*-[[:space:]]*id:[[:space:]]*"\([^"]*\)".*/\1/p' "$registry"
}

preset_default_packs() {
	# Enumerate pack ids whose default_in_preset list includes the given
	# preset, via a deterministic line scan (no YAML module dependency).
	local home_path="$1"
	local preset="$2"
	[[ -z "$home_path" ]] && return 0
	local registry="${home_path}/${PACK_REGISTRY_REL_PATH}"
	[[ -f "$registry" ]] || return 0
	local id="" line trimmed
	while IFS= read -r line || [[ -n "$line" ]]; do
		trimmed="${line#"${line%%[![:space:]]*}"}"
		case "$trimmed" in
			'#'*) ;;
			'- id:'*)
				id="${trimmed#*'"'}"
				id="${id%%'"'*}"
				;;
			'default_in_preset:'*)
				case "$trimmed" in
					*'"'"$preset"'"'*) [[ -n "$id" ]] && printf '%s\n' "$id" ;;
				esac
				id=""
				;;
		esac
	done < "$registry"
}

PACK_DETECT_NAMES=()
PACK_DETECT_STATUS=()
PACK_DETECT_VERSION=()

pack_detect_status() {
	# Per-pack presence + version detection (114.001-T / 47971057 bounded).
	# Detection only: no install/upgrade/provisioning. Appends to the global
	# parallel PACK_DETECT_* arrays with status one of:
	#   present       -> command found AND `--version` produced parseable output
	#   undetectable  -> command found but `--version` produced no output
	#   absent        -> command not found (and, for graphtor-docs, no
	#                    workspace-local .graphtor/bin/ binary either)
	local mcp="$1" exe="" version="" status="absent"
	if command -v "$mcp" >/dev/null 2>&1; then
		exe="$mcp"
	elif [[ "$mcp" == "graphtor-docs" ]]; then
		# graphtor-docs may be installed workspace-local at .graphtor/bin/ (registry eligibility signal), not just on PATH.
		if [[ -f ".graphtor/bin/graphtor-docs" && -x ".graphtor/bin/graphtor-docs" ]]; then exe=".graphtor/bin/graphtor-docs"
		elif [[ -f ".graphtor/bin/graphtor-docs.exe" && -x ".graphtor/bin/graphtor-docs.exe" ]]; then exe=".graphtor/bin/graphtor-docs.exe"
		fi
	fi
	if [[ -n "$exe" ]]; then
		local raw_output=""
		# Capture the version command's own exit status via command substitution
		# assignment (not a pipe to `head`), so a broken runtime that exits
		# nonzero is never misreported as "present" just because it wrote
		# something to stdout before failing.
		if raw_output="$("$exe" --version 2>/dev/null)"; then
			version="$(printf '%s\n' "$raw_output" | head -n1 | xargs 2>/dev/null || true)"
		fi
		if [[ -n "$version" ]]; then status="present"; else status="undetectable"; fi
	fi
	PACK_DETECT_NAMES+=("$mcp")
	PACK_DETECT_STATUS+=("$status")
	PACK_DETECT_VERSION+=("$version")
}

pack_recommended_action() {
	# Report-only classification (114.002-T / 47971057 bounded). Never executes
	# any install/upgrade -- "needs-install" is a deferred recommendation only.
	case "$1" in
		present) echo "retain-present" ;;
		absent) echo "needs-install (deferred)" ;;
		*) echo "unsupported-undetectable" ;;
	esac
}

# ── Phase 1: preflight ──────────────────────────────────────────────────────
invoke_preflight() {
	phase "preflight"
	local hard_missing=""
	if command -v python >/dev/null 2>&1; then PYTHON_BIN="python"; ok "python present"
	elif command -v python3 >/dev/null 2>&1; then PYTHON_BIN="python3"; ok "python3 present"
	else fail "python missing (required)"; hard_missing="$hard_missing python"; fi
	if command -v git >/dev/null 2>&1; then ok "git present"; else fail "git missing (required)"; hard_missing="$hard_missing git"; fi
	if command -v gh >/dev/null 2>&1; then ok "gh present"; else warn "gh not found (optional; needed for PR automation)"; fi

	local cli_tool=""
	case "$REGISTER" in copilot-cli) cli_tool="copilot" ;; claude) cli_tool="claude" ;; codex) cli_tool="codex" ;; esac
	if [[ -n "$cli_tool" ]]; then
		if command -v "$cli_tool" >/dev/null 2>&1; then ok "$cli_tool present"; else warn "$cli_tool not found (needed to register the $REGISTER environment)"; fi
	fi

	# Pack MCP prereqs are advisory: the deploy path seeds config and hands off;
	# missing MCP tools do not block scaffolding. Detection ALSO records version
	# (114.001-T / 47971057 bounded) for the pre-merge-install checklist phase.
	PACK_DETECT_NAMES=()
	PACK_DETECT_STATUS=()
	PACK_DETECT_VERSION=()
	for mcp in backlogit engram graphtor-docs; do
		pack_detect_status "$mcp"
		local idx=$((${#PACK_DETECT_NAMES[@]} - 1))
		case "${PACK_DETECT_STATUS[$idx]}" in
			present) ok "$mcp MCP prereq present (version: ${PACK_DETECT_VERSION[$idx]})" ;;
			undetectable) warn "$mcp present but version undetectable (optional pack MCP prereq)" ;;
			*) info "$mcp not found (optional pack MCP prereq)" ;;
		esac
	done

	if [[ -n "$hard_missing" ]]; then fail "Missing hard prerequisites:$hard_missing"; return 1; fi
	ok "preflight passed"
	return 0
}

# ── Phase (additive, 114-F / 47971057 bounded): checklist ───────────────────
invoke_checklist() {
	phase "checklist (pre-merge-install; report only)"
	if [[ "${#PACK_DETECT_NAMES[@]}" -eq 0 ]]; then
		info "no pack detection results available; skipping checklist."
		return 0
	fi

	# Interactive prompts are opt-in AND require a real terminal on stdin;
	# otherwise fall back to the non-interactive report (AC F3: headless/CI
	# deploys never regress and never block on stdin).
	local do_interactive=0
	if [[ "$INTERACTIVE" -eq 1 && -t 0 ]]; then do_interactive=1; fi

	printf '\n  Pre-merge-install checklist (REPORT ONLY -- no install/upgrade is executed):\n'
	printf '  %-16s %-14s %-10s %-24s %-10s\n' "PACK" "DETECTED" "VERSION" "RECOMMENDED-ACTION" "SELECTED"
	local i pack status version action selected default_ans answer
	for ((i = 0; i < ${#PACK_DETECT_NAMES[@]}; i++)); do
		pack="${PACK_DETECT_NAMES[$i]}"
		status="${PACK_DETECT_STATUS[$i]}"
		version="${PACK_DETECT_VERSION[$i]}"
		[[ -z "$version" ]] && version="-"
		action="$(pack_recommended_action "$status")"
		selected="n/a"
		if [[ "$do_interactive" -eq 1 ]]; then
			default_ans="n"; [[ "$status" == "present" ]] && default_ans="y"
			read -r -p "  Include $pack in install plan? [$default_ans] " answer || answer=""
			[[ -z "$answer" ]] && answer="$default_ans"
			case "$answer" in y|Y|yes|YES) selected="included" ;; *) selected="excluded" ;; esac
		fi
		printf '  %-16s %-14s %-10s %-24s %-10s\n' "$pack" "$status" "$version" "$action" "$selected"
	done
	printf '\n'
	info "Capability-pack runtime provisioning, when implemented, MUST occur BEFORE merge-install composition. Actual install/upgrade execution and all supply-chain/source/OS-matrix design remain DEFERRED to operator -- see docs/decisions/2026-08-07-capability-pack-runtime-installer-deliberation.md."
	return 0
}

# ── Phase 2: bootstrap ──────────────────────────────────────────────────────
RESOLVED_HOME=""
invoke_bootstrap() {
	phase "bootstrap"
	local resolved
	resolved="$(resolve_home)"
	if [[ -n "$resolved" && -d "$resolved" ]]; then
		ok "autoharness_home found: $resolved (reusing; idempotent skip)"
		RESOLVED_HOME="$resolved"; return 0
	fi

	info "autoharness_home not found."
	if [[ "$DRY_RUN" -eq 1 ]]; then
		info "[dry-run] would install autoharness globally via '$INSTALL_METHOD' (out-of-cwd; a real run also requires the --bootstrap opt-in)."
		RESOLVED_HOME="$AUTOHARNESS_HOME_DEFAULT"; return 0
	fi
	if [[ "$BOOTSTRAP" -ne 1 ]]; then
		warn "Global install is out-of-cwd and requires the explicit --bootstrap opt-in. Re-run with --bootstrap to install via '$INSTALL_METHOD', or set --home / AUTOHARNESS_HOME to an existing install."
		return 1
	fi

	case "$INSTALL_METHOD" in
		pip) info "Installing autoharness via pip (global tool)..."; if ! "${PYTHON_BIN:-python}" -m pip install --upgrade autoharness; then fail "pip install failed"; return 1; fi ;;
		clone) info "Cloning autoharness to $AUTOHARNESS_HOME_DEFAULT ..."; if ! git clone https://github.com/softwaresalt/autoharness "$AUTOHARNESS_HOME_DEFAULT"; then fail "git clone failed"; return 1; fi ;;
	esac
	resolved="$(resolve_home)"
	if [[ -n "$resolved" ]]; then ok "autoharness_home installed: $resolved"; RESOLVED_HOME="$resolved"; return 0; fi
	fail "bootstrap failed: autoharness_home still unresolved after install."
	return 1
}

# ── Phase 3: register ───────────────────────────────────────────────────────
invoke_register() {
	phase "register"
	if [[ "$REGISTER" == "none" ]]; then info "register skipped (--register none)"; return 0; fi

	local cmd=""
	case "$REGISTER" in
		vscode) cmd="setup-vscode" ;;
		copilot-cli) cmd="plugin" ;;
		claude) cmd="setup-claude" ;;
		codex) cmd="setup-codex" ;;
	esac

	if [[ "$DRY_RUN" -eq 1 ]]; then
		if [[ "$REGISTER" == "copilot-cli" ]]; then info "[dry-run] would run: copilot plugin marketplace add softwaresalt/autoharness && copilot plugin install autoharness@autoharness"; else info "[dry-run] would run: autoharness $cmd"; fi
		return 0
	fi

	if [[ "$REGISTER" == "copilot-cli" ]]; then
		if copilot plugin marketplace add softwaresalt/autoharness && copilot plugin install autoharness@autoharness; then ok "registered $REGISTER environment"; return 0; else fail "register failed"; return 1; fi
	elif command -v autoharness >/dev/null 2>&1; then
		autoharness "$cmd" && { ok "registered $REGISTER environment"; return 0; } || { fail "register failed"; return 1; }
	else
		warn "autoharness CLI not on PATH; skipping register (run 'autoharness $cmd' after bootstrap)."
		return 0
	fi
}

# ── Phase 4: scaffold ───────────────────────────────────────────────────────
invoke_scaffold() {
	phase "scaffold"
	local home_path="$1"
	local selected=()

	if [[ -z "$PACKS" ]]; then
		# OMITTED pack input -> resolve to the selected preset's default_in_preset members.
		while IFS= read -r id; do [[ -n "$id" ]] && selected+=("$id"); done < <(preset_default_packs "$home_path" "$PRESET")
		if [[ "$PRESET" == "starter" ]]; then
			info "starter preset with no explicit packs: no capability packs by default."
		elif [[ "${#selected[@]}" -eq 0 ]]; then
			warn "Could not enumerate preset defaults from the registry; writing config with no packs."
		else
			ok "enumerated ${#selected[@]} default packs for preset '$PRESET'"
		fi
	elif [[ "$PACKS" == "all" ]]; then
		while IFS= read -r id; do [[ -n "$id" ]] && selected+=("$id"); done < <(registry_packs "$home_path")
		if [[ "${#selected[@]}" -eq 0 ]]; then warn "Could not enumerate packs from the registry; writing config with no packs."; else ok "enumerated ${#selected[@]} packs from registry"; fi
	else
		local registry_list
		registry_list="$(registry_packs "$home_path")"
		if [[ -z "$registry_list" ]]; then warn "registry unavailable; cannot validate --packs entries against it."; fi
		local p
		IFS=',' read -ra requested <<< "$PACKS"
		for p in "${requested[@]}"; do
			p="$(echo "$p" | xargs)"
			[[ -z "$p" ]] && continue
			if [[ -n "$registry_list" ]] && ! grep -qx "$p" <<< "$registry_list"; then
				fail "Unknown pack '$p' (not in registry)."; return 1
			fi
			selected+=("$p")
		done
	fi

	local autoharness_dir="${WORKSPACE_ROOT}/.autoharness"
	local config_path="${autoharness_dir}/config.yaml"

	local body
	body="schema_version: \"1.0.0\"
preset: ${PRESET}"
	if [[ "${#selected[@]}" -gt 0 ]]; then
		body="${body}
capability_packs:"
		for p in "${selected[@]}"; do body="${body}
  - ${p}"; done
	else
		body="${body}
capability_packs: []"
	fi
	body="${body}
"

	if [[ "$DRY_RUN" -eq 1 ]]; then
		info "[dry-run] would write $config_path with preset '$PRESET' and ${#selected[@]} packs."
		return 0
	fi

	if [[ -L "$autoharness_dir" || -L "$config_path" ]]; then fail "refusing to write: .autoharness or config.yaml is a symlink (cwd containment)."; return 1; fi

	mkdir -p "$autoharness_dir"

	if [[ -f "$config_path" ]]; then
		local stamp backup
		stamp="$(date +%Y%m%d-%H%M%S)"
		backup="${config_path}.${stamp}.bak"
		cp "$config_path" "$backup"
		ok "backed up existing config to $backup"
		if [[ "$FORCE" -ne 1 ]]; then
			warn "config.yaml exists; not overwriting without --force (backup written). Re-run with --force to replace."
			return 0
		fi
	fi

	printf '%s' "$body" > "$config_path"
	ok "wrote $config_path"

	if [[ -f "${WORKSPACE_ROOT}/.env.local" ]]; then info ".env.local present; left untouched (never clobbered)."; fi
	return 0
}

# ── Phase 5: compose (HANDOFF ONLY) ─────────────────────────────────────────
invoke_compose() {
	phase "compose (handoff)"
	info "Template composition is an AI-agent reasoning task and is NOT performed by this script."
	printf '\n  Next step — run the harness installer agent:\n'
	printf '    /install-harness preset=%s\n\n' "$PRESET"
	info "The auto-mergeinstall agent will discover the workspace profile, compose templates, resolve variables, and run adversarial verification."
	return 0
}

# ── Phase 6: verify ─────────────────────────────────────────────────────────
invoke_verify() {
	phase "verify"
	if ! command -v autoharness >/dev/null 2>&1; then info "autoharness CLI not on PATH; skipping deterministic verify."; return 0; fi
	if [[ ! -f "${WORKSPACE_ROOT}/.autoharness/harness-manifest.yaml" ]]; then info "no harness manifest yet (composition not run); skipping deterministic verify."; return 0; fi
	if [[ "$DRY_RUN" -eq 1 ]]; then info "[dry-run] would run: autoharness verify-workspace --workspace $WORKSPACE_ROOT"; return 0; fi
	if autoharness verify-workspace --workspace "$WORKSPACE_ROOT"; then ok "verify-workspace completed (see .autoharness reports)"; return 0; else fail "verify failed"; return 1; fi
}

# ── Orchestration ───────────────────────────────────────────────────────────
printf 'autoharness deploy-harness — workspace: %s\n' "$WORKSPACE_ROOT"
[[ "$DRY_RUN" -eq 1 ]] && printf 'DRY RUN — no mutations will be performed.\n'

invoke_preflight || exit 1
invoke_checklist
invoke_bootstrap || exit 2
invoke_register || exit 3
invoke_scaffold "$RESOLVED_HOME" || exit 4
invoke_compose
invoke_verify || exit 5

printf '\n'
ok "deploy-harness completed. Run '/install-harness preset=${PRESET}' to compose the harness."
exit 0
