#!/usr/bin/env bash
# pre-commit-pipeline-topology.sh
# Generated by autoharness | Template: pre-commit-pipeline-topology.sh.tmpl
#
# Pre-commit hook: runs the deterministic `autoharness gate pipeline-topology`
# ambient check before a commit. This is the commit-time half of the P-001
# (at-most-one-active-shipment) / P-016 (single implementation worktree)
# local-gating pair; `pre-push-quality-gates.sh` (B1) covers the push-time
# invocation.
#
# NON-SHIPMENT-SCOPED INVOCATION: no human-supplied --shipment is passed. The
# gate deterministically resolves its target (the currently-claimed active
# shipment from backlogit, or the current branch slug) and always runs
# `--phase ambient` here (at-most-one-active, validating the resolved target
# when one exists). No resolvable claimed shipment / zero active shipments ->
# PASSES (existence-guarded, non-blocking for ordinary commits with no
# claimed shipment); a mismatched single active or two-or-more-active
# shipments still blocks fail-closed regardless of the advisory toggle below.
#
# Behavior:
#   * Absent 'autoharness' -> warn+skip, never a hard failure.
#   * Advisory-first by default (staged rollout): a gate failure warns but
#     does NOT block the commit unless AUTOHARNESS_TOPOLOGY_GATE_BLOCKING=true
#     is set in the environment.
#   * Single deterministic pass — no retry loop.
#
# Install (opt-in — the harness never silently overwrites your .git/hooks):
#   Git invokes the hook by the exact name `pre-commit` (no extension) under
#   the active hooks path, so this script must be INSTALLED AS `pre-commit`:
#     * Default hooks path:
#         cp <this> .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
#     * Or a dedicated hooks directory referenced by core.hooksPath, where the
#       file (or a dispatcher that execs it) is named `pre-commit`:
#         install -m 0755 <this> <hooks-dir>/pre-commit
#         git config core.hooksPath <hooks-dir>
#   If another pre-commit check (e.g. pre-commit-markdownlint.sh) already
#   occupies `pre-commit`, chain both from a single dispatcher rather than
#   overwriting one with the other.
#   To bypass once: git commit --no-verify

set -uo pipefail

# Run from repo root so repo-root-relative gate invocation is valid.
cd "$(git rev-parse --show-toplevel)" || exit 1

if ! command -v autoharness >/dev/null 2>&1; then
  echo "WARNING: 'autoharness' not found — skipping pipeline-topology gate." >&2
  exit 0
fi

echo "[Pipeline-Topology] autoharness gate pipeline-topology --mode manual --phase ambient"
if ! autoharness gate pipeline-topology --mode manual --phase ambient; then
  if [ "${AUTOHARNESS_TOPOLOGY_GATE_BLOCKING:-false}" = "true" ]; then
    echo "ERROR: pipeline-topology gate failed — commit blocked (P-001/P-016)." >&2
    exit 1
  fi
  echo "WARNING: pipeline-topology gate failed (advisory) — commit not blocked." >&2
  echo "  Set AUTOHARNESS_TOPOLOGY_GATE_BLOCKING=true to enforce, or commit --no-verify to bypass entirely." >&2
fi

exit 0
