# pre-commit-markdownlint.ps1
# Generated by autoharness | Template: pre-commit-markdownlint.ps1.tmpl
#
# Pre-commit hook: runs markdownlint on staged .md files.
# Exit code 1 on violations; 0 when all files pass.
#
# Install: register as a pre-commit hook or invoke from .git/hooks/pre-commit

$ErrorActionPreference = 'Stop'

# Run from repo root so repo-root-relative paths from git are valid
$RepoRoot = & git rev-parse --show-toplevel
Set-Location $RepoRoot

# Collect staged .md files
$StagedMd = git diff --cached --name-only --diff-filter=ACMR |
    Where-Object { $_ -match '\.md$' }

if (-not $StagedMd) {
    exit 0
}

# Verify markdownlint-cli is available
if (-not (Get-Command markdownlint -ErrorAction SilentlyContinue)) {
    Write-Warning "markdownlint-cli not found — skipping Markdown lint check."
    Write-Warning "Install with: npm install -g markdownlint-cli"
    exit 0
}

Write-Host "Running markdownlint on staged Markdown files..."
markdownlint @StagedMd
$ExitCode = $LASTEXITCODE

if ($ExitCode -ne 0) {
    Write-Error "markdownlint violations detected (P-008). Fix heading hierarchy issues before committing."
    exit 1
}

exit 0
