# pre-push-quality-gates.ps1
# Generated by autoharness | Template: pre-push-quality-gates.ps1.tmpl
#
# Pre-push hook: runs the workspace's discovered local quality gates
# (lint, format, typecheck, test, build) before a push and BLOCKS the push
# (exit 1) if any gate fails. This is the local half of the unified CI +
# local-gating primitive (P-019): because remote CI is intentionally minimal
# and Linux-only, local verification is the primary gate before push.
#
# Behavior:
#   * Absent gates are omitted at install time (only discovered gates appear).
#   * If a gate's tool is not installed on this machine, the gate is SKIPPED
#     with a warning (tool-not-found -> warn+skip), never a hard failure.
#   * Single deterministic pass — NO retry loop, so the hook cannot spin
#     (circuit-breaker compatible). A failing gate surfaces immediately.
#
# Install (opt-in — the harness never silently overwrites your .git/hooks):
#   Git invokes the hook by the exact name `pre-push` (no extension) under the
#   active hooks path, and runs it with a POSIX shell — not PowerShell. So this
#   .ps1 cannot be git's hook directly; register a POSIX `pre-push` that execs it:
#     * .git/hooks/pre-push (or <hooks-dir>/pre-push) containing:
#         #!/bin/sh
#         exec pwsh -NoProfile -File "$(dirname "$0")/pre-push-quality-gates.ps1" "$@"
#       then, for a dedicated directory:
#         git config core.hooksPath <hooks-dir>
#   Pointing core.hooksPath at a directory that only contains the .ps1/.sh
#   variants will NOT work — git looks specifically for `<dir>/pre-push`.
#   To bypass once (e.g. an emergency push): git push --no-verify
#
# NOTE: gate commands must use PowerShell-appropriate syntax on Windows. Express
# environment prefixes with `$env:VAR = '...'` rather than the POSIX
# `VAR=value command` form (which PowerShell does not parse). When a gate command
# needs shell-specific syntax, the installer renders the PowerShell form here and
# the POSIX form in the .sh variant; portable commands (e.g. `mypy src/`,
# `npm test`) are rendered identically in both.

$ErrorActionPreference = 'Continue'

# Run from repo root so repo-root-relative gate commands are valid.
$RepoRoot = & git rev-parse --show-toplevel
Set-Location $RepoRoot

$script:Failed = $false

# Invoke-Gate <label> <tool> <command>
# Probes <tool> — the discovered gate binary whose absence means "skip". When
# <tool> is empty, falls back to the command's leading real token (skipping
# leading `$env:VAR = '...'` / `VAR=value` env prefixes). Explicit tool metadata
# makes wrapper commands such as `python -m mypy` skip correctly when the REAL
# tool is absent, instead of running the wrapper and blocking the push. Warns and
# skips when the tool is absent; otherwise runs the command once and records a
# failure without aborting the rest.
function Invoke-Gate {
    param(
        [string]$Label,
        [string]$Tool,
        [string]$Command
    )

    if ([string]::IsNullOrWhiteSpace($Command)) {
        return
    }

    $probe = $Tool
    if ([string]::IsNullOrWhiteSpace($probe)) {
        foreach ($tok in ($Command -split '\s+')) {
            if ($tok -match '=' -or $tok -like '$env:*') { continue }
            $probe = $tok
            break
        }
    }

    if ($probe -and -not (Get-Command $probe -ErrorAction SilentlyContinue)) {
        Write-Warning "'$probe' not found — skipping $Label gate."
        return
    }

    Write-Host "[$Label] $Command"
    Invoke-Expression $Command
    if ($LASTEXITCODE -ne 0) {
        Write-Error "$Label gate failed — push blocked (P-019)."
        $script:Failed = $true
    }
}

Write-Host "Running local pre-push quality gates..."

Invoke-Gate "Lint" "go vet" "go vet ./..."
Invoke-Gate "Format" "gofmt" ""
Invoke-Gate "Typecheck" "" ""
Invoke-Gate "Test" "go test" "go test ./..."
Invoke-Gate "Build" "go" "go vet ./..."

# Pipeline-topology gate (P-001/P-016 ambient invariant check).
#
# NON-SHIPMENT-SCOPED INVOCATION: no human-supplied --shipment is passed.
# The gate deterministically resolves its target (the currently-claimed
# active shipment from backlogit, or the current branch slug) and always
# runs `--phase ambient` here (at-most-one-active, validating the
# resolved target when one exists). No resolvable claimed shipment / zero
# active shipments -> PASSES (existence-guarded, non-blocking); a
# mismatched single active or two-or-more-active shipments still blocks
# fail-closed regardless of the advisory toggle below.
#
# Advisory-first by default (staged rollout): a gate failure warns but
# does NOT block the push unless $env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING
# is 'true'. Single deterministic pass — no retry loop (circuit-breaker
# compatible). Absent 'autoharness' -> warn+skip, never a hard failure.
if (Get-Command autoharness -ErrorAction SilentlyContinue) {
    Write-Host "[Pipeline-Topology] autoharness gate pipeline-topology --mode manual --phase ambient"
    autoharness gate pipeline-topology --mode manual --phase ambient
    if ($LASTEXITCODE -ne 0) {
        if ($env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING -eq 'true') {
            Write-Error "pipeline-topology gate failed — push blocked (P-001/P-016)."
            $script:Failed = $true
        } else {
            Write-Warning "pipeline-topology gate failed (advisory) — push not blocked."
            Write-Warning "  Set `$env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING = 'true' to enforce, or push --no-verify to bypass entirely."
        }
    }
} else {
    Write-Warning "'autoharness' not found — skipping pipeline-topology gate."
}

if ($script:Failed) {
    Write-Error "One or more quality gates failed. Fix them, or push with --no-verify to bypass."
    exit 1
}

Write-Host "All local quality gates passed."
exit 0
