#!/usr/bin/env bash
# pre-push-quality-gates.sh
# Generated by autoharness | Template: pre-push-quality-gates.sh.tmpl
#
# Pre-push hook: runs the workspace's discovered local quality gates
# (lint, format, typecheck, test, build) before a push and BLOCKS the push
# (exit 1) if any gate fails. This is the local half of the unified CI +
# local-gating primitive (P-019): because remote CI is intentionally minimal
# and Linux-only, local verification is the primary gate before push.
#
# Behavior:
#   * Absent gates are omitted at install time (only discovered gates appear).
#   * If a gate's tool is not installed on this machine, the gate is SKIPPED
#     with a warning (tool-not-found -> warn+skip), never a hard failure.
#   * Single deterministic pass — NO retry loop, so the hook cannot spin
#     (circuit-breaker compatible). A failing gate surfaces immediately.
#
# Install (opt-in — the harness never silently overwrites your .git/hooks):
#   Git invokes the hook by the exact name `pre-push` (no extension) under the
#   active hooks path, so this script must be INSTALLED AS `pre-push`:
#     * Default hooks path:
#         cp <this> .git/hooks/pre-push && chmod +x .git/hooks/pre-push
#     * Or a dedicated hooks directory referenced by core.hooksPath, where the
#       file (or a dispatcher that execs it) is named `pre-push`:
#         install -m 0755 <this> <hooks-dir>/pre-push
#         git config core.hooksPath <hooks-dir>
#   Pointing core.hooksPath at a directory that only contains
#   `pre-push-quality-gates.sh` will NOT work — git looks for `<dir>/pre-push`.
#   To bypass once (e.g. an emergency push): git push --no-verify
#
# git passes "<remote> <url>" as arguments and ref lines on stdin; a quality
# gate runs regardless of what is being pushed, so stdin is drained and ignored.

set -uo pipefail

# Run from repo root so repo-root-relative gate commands are valid.
cd "$(git rev-parse --show-toplevel)" || exit 1

# Drain stdin (ref updates) so git does not see a broken pipe.
cat >/dev/null 2>&1 || true

FAILED=0

# run_gate <label> <probe_tool> <command>
# Probes <probe_tool> — the discovered gate binary whose absence means "skip".
# When <probe_tool> is empty, falls back to the command's leading real token
# (skipping leading VAR=value env prefixes). Explicit probe metadata makes
# wrapper commands such as `python -m mypy` or `npm run lint` skip correctly when
# the REAL tool (mypy, the lint script) is absent, instead of running the wrapper
# and blocking the push. Warns and skips when the tool is absent; otherwise runs
# the command once and records a failure without aborting the remaining gates.
run_gate() {
  label="$1"
  probe="$2"
  cmd="$3"

  # Nothing to do when the installer resolved no command for this gate.
  [ -n "$cmd" ] || return 0

  # Fall back to deriving the probe from the command's leading real token.
  if [ -z "$probe" ]; then
    for tok in $cmd; do
      case "$tok" in
        *=*) continue ;;
        *) probe="$tok"; break ;;
      esac
    done
  fi

  if [ -n "$probe" ] && ! command -v "$probe" >/dev/null 2>&1; then
    echo "WARNING: '$probe' not found — skipping $label gate." >&2
    return 0
  fi

  echo "[$label] $cmd"
  if ! sh -c "$cmd"; then
    echo "ERROR: $label gate failed — push blocked (P-019)." >&2
    FAILED=1
  fi
}

echo "Running local pre-push quality gates..."

run_gate "Lint" "go vet" "go vet ./..."
run_gate "Format" "gofmt" ""
run_gate "Typecheck" "" ""
run_gate "Test" "go test" "go test ./..."
run_gate "Build" "go" "go vet ./..."

# Pipeline-topology gate (P-001/P-016 ambient invariant check).
#
# NON-SHIPMENT-SCOPED INVOCATION: no human-supplied --shipment is passed.
# The gate deterministically resolves its target (the currently-claimed
# active shipment from backlogit, or the current branch slug) and always
# runs `--phase ambient` here (at-most-one-active, validating the
# resolved target when one exists). No resolvable claimed shipment / zero
# active shipments -> PASSES (existence-guarded, non-blocking); a
# mismatched single active or two-or-more-active shipments still blocks
# fail-closed regardless of the advisory toggle below.
#
# Advisory-first by default (staged rollout): a gate failure warns but
# does NOT block the push unless AUTOHARNESS_TOPOLOGY_GATE_BLOCKING=true
# is set in the environment. This is a single deterministic pass — no
# retry loop — so the hook cannot spin (circuit-breaker compatible).
# Absent 'autoharness' -> warn+skip, never a hard failure.
if command -v autoharness >/dev/null 2>&1; then
  echo "[Pipeline-Topology] autoharness gate pipeline-topology --mode manual --phase ambient"
  if ! autoharness gate pipeline-topology --mode manual --phase ambient; then
    if [ "${AUTOHARNESS_TOPOLOGY_GATE_BLOCKING:-false}" = "true" ]; then
      echo "ERROR: pipeline-topology gate failed — push blocked (P-001/P-016)." >&2
      FAILED=1
    else
      echo "WARNING: pipeline-topology gate failed (advisory) — push not blocked." >&2
      echo "  Set AUTOHARNESS_TOPOLOGY_GATE_BLOCKING=true to enforce, or push --no-verify to bypass entirely." >&2
    fi
  fi
else
  echo "WARNING: 'autoharness' not found — skipping pipeline-topology gate." >&2
fi

if [ "$FAILED" -ne 0 ]; then
  echo "One or more quality gates failed. Fix them, or push with --no-verify to bypass." >&2
  exit 1
fi

echo "All local quality gates passed."
exit 0
