#!/usr/bin/env bash
# pre-commit-markdownlint.sh
# Generated by autoharness | Template: pre-commit-markdownlint.sh.tmpl
#
# Pre-commit hook: runs markdownlint on staged .md files.
# Exit code 1 on violations; 0 when all files pass.
#
# Install: copy to .git/hooks/pre-commit (or register via .pre-commit-config.yaml)

set -uo pipefail

# Run from repo root so repo-root-relative paths from git are valid
cd "$(git rev-parse --show-toplevel)"

# Collect staged .md files using NUL delimiters (handles spaces in paths)
STAGED_MD_FILES=()
while IFS= read -r -d '' f; do
  STAGED_MD_FILES+=("$f")
done < <(git diff --cached --name-only -z --diff-filter=ACMR | grep -zE '\.md$' || true)

if [ ${#STAGED_MD_FILES[@]} -eq 0 ]; then
  exit 0
fi

# Verify markdownlint-cli is available
if ! command -v markdownlint &>/dev/null; then
  echo "WARNING: markdownlint-cli not found — skipping Markdown lint check." >&2
  echo "Install with: npm install -g markdownlint-cli" >&2
  exit 0
fi

echo "Running markdownlint on staged Markdown files..."
markdownlint "${STAGED_MD_FILES[@]}" || {
  echo "ERROR: markdownlint violations detected (P-008). Fix heading hierarchy issues before committing." >&2
  exit 1
}

exit 0
